1383 fix on client side
CityofOttawa/Popup_Survey pull request #4
Opened 2017-03-23 19:52 UTC by elcazador

Revised fix for issue 1383. Bot/crawler detection now occurs on client
side using most common known bots and crawlers.  This will not exclude
other crawlers.  Using a blacklist is probably desirable to whitelisting browsers and having to spend time maintaining the white list when complaints come in.

Made minor change to have the survey panel be hidden by default and only
shown when needed.  This fixed a screen flicker that happened when the
popup was rendered and then hidden on slower machines.

2017-03-23 19:58 UTC, minorOffense requested changes

2017-03-23 19:58 UTC, minorOffense commented on js/popup_survey.js
> +    if( navigator.userAgent.match(bots) ) {
Only thing I would add is to check that navigator.userAgent isn't undefined. I remember something about that being deprecated or changing or something...

2017-03-23 19:58 UTC, minorOffense commented on popup_survey.module
> +  if( count($result) > 0 ) {
I'd do an isset or is_array on bean instead

2017-03-24 12:26 UTC, elcazador commented on popup_survey.module
> +  if( count($result) > 0 ) {
I tried isset first and then is_array but the query result is always an array, just an empty one so they  always returns true.  This is a check for the existence of data, not a failed query.

2017-03-24 13:00 UTC, minorOffense approved these changes

2017-03-24 18:56 UTC, closed without merging

2017-03-27 18:56 UTC, minorOffense commented on popup_survey.module
>        // DEBUG: dpm($page['page_bottom']['popup_survey']);
should remove this dpm even if it's commented out.